name: Cypress Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.4
      - name: Cypress.io
        uses: cypress-io/github-action@v4.2.0
        with:
          unit-test: npm run test
          start: npm start
