name: Tests
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3.1.0
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        name: npm install
        run: npm ci
        name: unit tests
        run: npm run test
        name: run dev server
        run: npm start
        name: e2e test
        run: npm run e2e

