name: Cypress Test
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3.1.0
        name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: tests
        run: npm run test
      - uses: cypress-io/github-action@v4.2.0
        name: Cypress.io
        with:
          start: npm start
